[build]
  command = "npm install"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/server"
